name: amplify_storage_s3
description: The Amplify Flutter Storage category plugin using the AWS S3 provider.
version: 1.0.0-next.1+1
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/next/packages/storage/amplify_storage_s3
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

# Helps `pana` since we do not use Flutter plugins for most platforms
platforms:
  ios:
  android:
  macos:
  windows:
  linux:
  web:

dependencies:
  amplify_core:
    git:
      url: https://github.com/landyrev/amplify-flutter
      ref: savvynavvy
      path: packages/amplify_core
  amplify_db_common:
    git:
      url: https://github.com/landyrev/amplify-flutter
      ref: savvynavvy
      path: packages/common/amplify_db_common
  amplify_storage_s3_dart:
    git:
      url: https://github.com/landyrev/amplify-flutter
      ref: savvynavvy
      path: packages/storage/amplify_storage_s3_dart
  aws_common: ">=0.3.2 <0.4.0"
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path_provider: ^2.0.0

dev_dependencies:
  amplify_lints: ^2.0.0
  amplify_test:
    path: ../../amplify_test
  aws_signature_v4:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
