name: amplify_analytics_pinpoint
description: The Amplify Flutter Analytics category plugin using the AWS Pinpoint provider.
version: 1.0.0-next.1
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/next/packages/analytics/amplify_analytics_pinpoint
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

# Helps `pana` since we do not use Flutter plugins for most platforms
platforms:
  ios:
  android:
  macos:
  windows:
  linux:
  web:

dependencies:
  amplify_analytics_pinpoint_dart:
    git:
      url: https://github.com/landyrev/amplify-flutter
      ref: savvynavvy2
      path: packages/analytics/amplify_analytics_pinpoint_dart
  amplify_core:
    git:
      url: https://github.com/landyrev/amplify-flutter
      ref: savvynavvy2
      path: packages/amplify_core
  amplify_db_common:
    git:
      url: https://github.com/landyrev/amplify-flutter
      ref: savvynavvy2
      path: packages/common/amplify_db_common
  amplify_secure_storage: ">=0.1.3 <0.2.0"
  aws_common: ">=0.3.1 <0.4.0"
  device_info_plus: ^6.0.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  package_info_plus: ^2.0.0
  path_provider: ^2.0.0

dev_dependencies:
  amplify_lints: ^2.0.0
  flutter_test:
    sdk: flutter
